In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
result = arr * 2

In [5]:
result

array([ 2,  4,  6,  8, 10])

In [8]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([5,6,7,8])
result2 = arr1+arr2

In [10]:
result
result2


array([[ 6,  8, 10, 12],
       [10, 12, 14, 16]])