In [9]:
import numpy as np

arr1 = np.array([1,2,3,3,4,"rhushi"])

In [10]:
arr1

array(['1', '2', '3', '3', '4', 'rhushi'], dtype='<U11')

In [13]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [14]:
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
type(arr2)

numpy.ndarray

In [17]:
arr2.shape

(2, 4)

In [24]:
list1 = [1,2,3,4]
list_squares =[x ** 2 for x in list1]
list_squares

[1, 4, 9, 16]

In [20]:
list_squares = arr2 ** 2

In [21]:
list_squares

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])