In [2]:
import numpy as np

In [14]:
arr =  np.array([[1,2,3],[4,5,6],[7,8,99]])

In [15]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [16]:
flat = arr.flatten()

In [17]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99])

In [18]:
flat[2]

3

In [19]:
flat[2:4]

array([3, 4])

In [20]:
mask =  arr >25
mask

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])