In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[0]

array([1, 2, 3])

In [7]:
arr[1]


array([4, 5, 6])

In [9]:
arr[2]

array([7, 8, 9])

In [10]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [11]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [12]:
arr[0][1]

2

In [13]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [14]:
arr3d = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[11,12,13]]])

In [15]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr3d[0,1,2]

6

# 